
-- MIGRATION: 20260221_consolidated_schema.sql
-- DESCRIPTION: Consolidated schema script for Transporte 2.0.
--              Includes all tables, RLS policies, and Cascade Delete constraints.
--              Idempotent: Safe to run multiple times.

BEGIN;

-- =================================================================================================
-- 1. EXTENSIONS
-- =================================================================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =================================================================================================
-- 2. TABLES (Create if not exists)
-- =================================================================================================

-- 2.1 Organizations
CREATE TABLE IF NOT EXISTS public.organizations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2.2 Profiles
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  organization_id UUID REFERENCES public.organizations(id),
  name TEXT,
  phone TEXT,
  role TEXT CHECK (role IN ('admin', 'user')) DEFAULT 'user',
  status TEXT CHECK (status IN ('pending', 'active', 'blocked')) DEFAULT 'pending',
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.3 Vehicles
CREATE TABLE IF NOT EXISTS public.vehicles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id UUID REFERENCES public.organizations(id) NOT NULL,
  name TEXT NOT NULL,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  year INTEGER NOT NULL,
  plate TEXT NOT NULL,
  type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'maintenance', 'out')),
  odometer INTEGER NOT NULL DEFAULT 0,
  fuel_level INTEGER NOT NULL DEFAULT 100 CHECK (fuel_level BETWEEN 0 AND 100),
  fuel_efficiency NUMERIC(4,1) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(organization_id, plate)
);

-- 2.4 Maintenance Records
CREATE TABLE IF NOT EXISTS public.maintenance_records (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  organization_id UUID REFERENCES public.organizations(id) NOT NULL,
  vehicle_id BIGINT REFERENCES public.vehicles(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  description TEXT NOT NULL,
  cost NUMERIC(10,2) NOT NULL DEFAULT 0,
  mechanic TEXT,
  type TEXT NOT NULL CHECK (type IN ('preventive', 'corrective')),
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.5 Conversations
CREATE TABLE IF NOT EXISTS public.conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  contact_name TEXT,
  contact_phone TEXT NOT NULL,
  status TEXT CHECK (status IN ('active', 'pending', 'closed')) DEFAULT 'pending',
  last_message TEXT,
  last_message_at TIMESTAMPTZ DEFAULT now(),
  assigned_to UUID REFERENCES public.profiles(id),
  flow_step TEXT,
  flow_data JSONB,
  is_bot_active BOOLEAN DEFAULT TRUE,
  unread_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2.6 Messages
CREATE TABLE IF NOT EXISTS public.messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL, -- FK added later to ensure CASCADE
  sender TEXT CHECK (sender IN ('agent', 'contact', 'system')) NOT NULL,
  content TEXT,
  type TEXT CHECK (type IN ('text', 'image', 'audio', 'file')) DEFAULT 'text',
  status TEXT CHECK (status IN ('sent', 'delivered', 'read')) DEFAULT 'sent',
  external_id TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2.7 Boarding Locations
CREATE TABLE IF NOT EXISTS public.boarding_locations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  neighborhood TEXT NOT NULL,
  point_name TEXT NOT NULL,
  description TEXT
);

-- 2.8 Registrations
CREATE TABLE IF NOT EXISTS public.registrations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  conversation_id UUID, -- FK added later to ensure CASCADE
  patient_name TEXT,
  patient_phone TEXT,
  procedure_date DATE,
  procedure_time TIME,
  procedure_type TEXT CHECK (procedure_type IN ('Exame', 'Consulta')),
  procedure_name TEXT,
  location TEXT,
  city TEXT,
  boarding_neighborhood TEXT,
  boarding_point TEXT,
  needs_companion BOOLEAN DEFAULT FALSE,
  companion_reason TEXT,
  attachment_url TEXT,
  status TEXT DEFAULT 'pending'
);

-- 2.9 System Settings
CREATE TABLE IF NOT EXISTS public.system_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  description TEXT,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.10 Audit Logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    organization_id UUID REFERENCES public.organizations(id),
    user_id UUID REFERENCES auth.users(id),
    action TEXT NOT NULL,
    entity TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    old_data JSONB,
    new_data JSONB,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2.11 WhatsApp Sessions
CREATE TABLE IF NOT EXISTS public.whatsapp_sessions (
    id VARCHAR(255) PRIMARY KEY,
    data JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- =================================================================================================
-- 3. CONSTRAINTS & INDEXES (Ensure correctness)
-- =================================================================================================

-- 3.1 Messages Foreign Key (CASCADE)
ALTER TABLE public.messages 
  DROP CONSTRAINT IF EXISTS messages_conversation_id_fkey;

ALTER TABLE public.messages
  ADD CONSTRAINT messages_conversation_id_fkey
  FOREIGN KEY (conversation_id)
  REFERENCES public.conversations(id)
  ON DELETE CASCADE;

-- 3.2 Registrations Foreign Key (CASCADE)
ALTER TABLE public.registrations 
  DROP CONSTRAINT IF EXISTS registrations_conversation_id_fkey;

ALTER TABLE public.registrations
  ADD CONSTRAINT registrations_conversation_id_fkey
  FOREIGN KEY (conversation_id)
  REFERENCES public.conversations(id)
  ON DELETE CASCADE;

-- Indexes (If not exists - PG doesn't have IF NOT EXISTS for indexes easily, so we drop/create or ignore errors)
-- Simplest way in a migration script is usually DROP IF EXISTS
DROP INDEX IF EXISTS idx_profiles_org;
CREATE INDEX idx_profiles_org ON public.profiles(organization_id);

DROP INDEX IF EXISTS idx_vehicles_org;
CREATE INDEX idx_vehicles_org ON public.vehicles(organization_id);

DROP INDEX IF EXISTS idx_conversations_last_message_at;
CREATE INDEX idx_conversations_last_message_at ON public.conversations(last_message_at DESC);

DROP INDEX IF EXISTS idx_conversations_contact_phone;
CREATE INDEX idx_conversations_contact_phone ON public.conversations(contact_phone);

DROP INDEX IF EXISTS idx_messages_conversation_id;
CREATE INDEX idx_messages_conversation_id ON public.messages(conversation_id);

-- =================================================================================================
-- 4. FUNCTIONS
-- =================================================================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, phone, role, status)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'phone',
    'user',
    'pending'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.get_auth_org_id()
RETURNS UUID AS $$
BEGIN
  RETURN (SELECT organization_id FROM public.profiles WHERE id = auth.uid());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() 
    AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =================================================================================================
-- 5. RLS POLICIES (Reset and Recreate)
-- =================================================================================================

-- Enable RLS
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boarding_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_sessions ENABLE ROW LEVEL SECURITY;

-- Helper macro to drop policies
DO $$ 
DECLARE 
    r RECORD; 
BEGIN 
    FOR r IN (SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public') LOOP 
        EXECUTE 'DROP POLICY IF EXISTS "' || r.policyname || '" ON public.' || r.tablename; 
    END LOOP; 
END $$;

-- 5.1 Organizations
CREATE POLICY "Tenant View Policy" ON public.organizations FOR SELECT USING (id = public.get_auth_org_id());

-- 5.2 Profiles
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admins can view all profiles" ON public.profiles FOR SELECT USING (public.is_admin());
CREATE POLICY "Admins can update all profiles" ON public.profiles FOR UPDATE USING (public.is_admin());

-- 5.3 Vehicles
CREATE POLICY "Tenant Isolation Policy" ON public.vehicles FOR ALL USING (organization_id = public.get_auth_org_id()) WITH CHECK (organization_id = public.get_auth_org_id());

-- 5.4 Conversations
CREATE POLICY "Users can view all conversations" ON public.conversations FOR SELECT USING (true);
CREATE POLICY "Users can update assigned conversations" ON public.conversations FOR UPDATE USING (auth.uid() = assigned_to OR public.is_admin());
CREATE POLICY "Admins can delete conversations" ON public.conversations FOR DELETE USING (public.is_admin());

-- 5.5 Messages
CREATE POLICY "Users can view all messages" ON public.messages FOR SELECT USING (true);
CREATE POLICY "Users can insert messages" ON public.messages FOR INSERT WITH CHECK (true);
-- Allow delete via cascade (handled by DB) or explicitly if needed, but usually RLS for delete on child is checked if user calls delete on child.
-- Since we delete parent (conversation), we need permission on conversation.
-- However, if we want to allow deleting individual messages:
CREATE POLICY "Admins can delete messages" ON public.messages FOR DELETE USING (public.is_admin());

-- 5.6 Registrations
CREATE POLICY "Users can view registrations" ON public.registrations FOR SELECT USING (true);
CREATE POLICY "Users can insert registrations" ON public.registrations FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update registrations" ON public.registrations FOR UPDATE USING (true);
CREATE POLICY "Admins can delete registrations" ON public.registrations FOR DELETE USING (public.is_admin());

-- 5.7 Boarding Locations
CREATE POLICY "Users can view boarding locations" ON public.boarding_locations FOR SELECT USING (true);
CREATE POLICY "Users can insert boarding locations" ON public.boarding_locations FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update boarding locations" ON public.boarding_locations FOR UPDATE USING (true);
CREATE POLICY "Users can delete boarding locations" ON public.boarding_locations FOR DELETE USING (true);

-- 5.8 System Settings
CREATE POLICY "Authenticated users can read system settings" ON public.system_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can update system settings" ON public.system_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 5.9 WhatsApp Sessions
CREATE POLICY "Service Role Access" ON public.whatsapp_sessions FOR ALL USING (true);

-- =================================================================================================
-- 6. DATA SEEDING
-- =================================================================================================

INSERT INTO public.system_settings (key, value, description)
VALUES 
  ('service_hours', '{"start": "08:00", "end": "18:00", "active": true}'::jsonb, 'Horário de Atendimento'),
  ('welcome_message', '"Olá! Bem-vindo ao nosso atendimento via WhatsApp. Como posso ajudar?"'::jsonb, 'Mensagem de Boas Vindas'),
  ('bot_notices', '""'::jsonb, 'Avisos Gerais para a IA')
ON CONFLICT (key) DO NOTHING;

COMMIT;
