-- Create vehicles table
create table public.vehicles (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null,
  model text not null,
  year integer not null,
  plate text not null unique,
  type text not null,
  status text not null default 'available' check (status in ('available', 'maintenance', 'out')),
  odometer integer not null default 0,
  fuel_level integer not null default 100 check (fuel_level between 0 and 100),
  fuel_efficiency numeric(4,1) not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create maintenance_records table
create table public.maintenance_records (
  id uuid default gen_random_uuid() primary key,
  vehicle_id bigint references public.vehicles(id) on delete cascade not null,
  date date not null,
  description text not null,
  cost numeric(10,2) not null default 0,
  mechanic text,
  type text not null check (type in ('preventive', 'corrective')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add indexes
create index vehicles_status_idx on public.vehicles(status);
create index maintenance_records_vehicle_id_idx on public.maintenance_records(vehicle_id);

-- Enable RLS
alter table public.vehicles enable row level security;
alter table public.maintenance_records enable row level security;

-- Create policies (assuming public access for simplicity based on project context, or authenticated)
-- For now, allow all authenticated users to read/write as it seems to be an internal tool
create policy "Enable all for authenticated users" on public.vehicles
  for all using (auth.role() = 'authenticated');

create policy "Enable all for authenticated users" on public.maintenance_records
  for all using (auth.role() = 'authenticated');
