-- MIGRATION: 20260223_consolidated_schema_final.sql
-- DESCRIPTION: Consolidated schema script for Transporte 2.0.
--              Includes all tables, RLS policies, and Cascade Delete constraints.
--              Idempotent: Safe to run multiple times.
--              Restores 'organization_id' support for compatibility with backend logic.

BEGIN;

-- =================================================================================================
-- 1. EXTENSIONS
-- =================================================================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =================================================================================================
-- 2. TABLES (Create if not exists)
-- =================================================================================================

-- 2.1 Organizations
CREATE TABLE IF NOT EXISTS public.organizations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2.2 Profiles
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  organization_id UUID REFERENCES public.organizations(id),
  name TEXT,
  phone TEXT,
  role TEXT CHECK (role IN ('admin', 'user', 'super_admin')) DEFAULT 'user',
  status TEXT CHECK (status IN ('pending', 'active', 'blocked')) DEFAULT 'pending',
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.3 Vehicles
CREATE TABLE IF NOT EXISTS public.vehicles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id UUID REFERENCES public.organizations(id),
  name TEXT NOT NULL,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  year INTEGER NOT NULL,
  plate TEXT NOT NULL,
  type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'maintenance', 'out')),
  odometer INTEGER NOT NULL DEFAULT 0,
  fuel_level INTEGER NOT NULL DEFAULT 100 CHECK (fuel_level BETWEEN 0 AND 100),
  fuel_efficiency NUMERIC(4,1) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(organization_id, plate)
);

-- 2.4 Maintenance Records
CREATE TABLE IF NOT EXISTS public.maintenance_records (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  organization_id UUID REFERENCES public.organizations(id),
  vehicle_id BIGINT REFERENCES public.vehicles(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  description TEXT NOT NULL,
  cost NUMERIC(10,2) NOT NULL DEFAULT 0,
  mechanic TEXT,
  type TEXT NOT NULL CHECK (type IN ('preventive', 'corrective')),
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.5 Conversations
CREATE TABLE IF NOT EXISTS public.conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID REFERENCES public.organizations(id), -- Added back for compatibility
  contact_name TEXT,
  contact_phone TEXT NOT NULL,
  status TEXT CHECK (status IN ('active', 'pending', 'closed')) DEFAULT 'pending',
  last_message TEXT,
  last_message_at TIMESTAMPTZ DEFAULT now(),
  assigned_to UUID REFERENCES public.profiles(id),
  flow_step TEXT,
  flow_data JSONB,
  is_bot_active BOOLEAN DEFAULT TRUE,
  unread_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2.6 Messages
CREATE TABLE IF NOT EXISTS public.messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID REFERENCES public.organizations(id), -- Added back for compatibility
  conversation_id UUID NOT NULL, 
  sender TEXT CHECK (sender IN ('agent', 'contact', 'system')) NOT NULL,
  content TEXT,
  type TEXT CHECK (type IN ('text', 'image', 'audio', 'file')) DEFAULT 'text',
  status TEXT CHECK (status IN ('sent', 'delivered', 'read', 'failed')) DEFAULT 'sent',
  external_id TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2.7 Boarding Locations
CREATE TABLE IF NOT EXISTS public.boarding_locations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  organization_id UUID REFERENCES public.organizations(id), -- Added back for compatibility
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  neighborhood TEXT NOT NULL,
  point_name TEXT NOT NULL,
  description TEXT
);

-- 2.8 Registrations
CREATE TABLE IF NOT EXISTS public.registrations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  organization_id UUID REFERENCES public.organizations(id), -- Added back for compatibility
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  conversation_id UUID,
  patient_name TEXT,
  patient_phone TEXT,
  procedure_date DATE,
  procedure_time TIME,
  procedure_type TEXT CHECK (procedure_type IN ('Exame', 'Consulta')),
  procedure_name TEXT,
  location TEXT,
  city TEXT,
  boarding_neighborhood TEXT,
  boarding_point TEXT,
  needs_companion BOOLEAN DEFAULT FALSE,
  companion_reason TEXT,
  attachment_url TEXT,
  status TEXT DEFAULT 'pending'
);

-- 2.9 System Settings
CREATE TABLE IF NOT EXISTS public.system_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  description TEXT,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.10 Audit Logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    organization_id UUID REFERENCES public.organizations(id),
    user_id UUID REFERENCES auth.users(id),
    action TEXT NOT NULL,
    entity TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    old_data JSONB,
    new_data JSONB,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2.11 WhatsApp Sessions
CREATE TABLE IF NOT EXISTS public.whatsapp_sessions (
    id VARCHAR(255) PRIMARY KEY,
    data JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- =================================================================================================
-- 3. CONSTRAINTS & INDEXES (Ensure correctness)
-- =================================================================================================

-- 3.1 Messages Foreign Key (CASCADE)
ALTER TABLE public.messages 
  DROP CONSTRAINT IF EXISTS messages_conversation_id_fkey;

ALTER TABLE public.messages
  ADD CONSTRAINT messages_conversation_id_fkey
  FOREIGN KEY (conversation_id)
  REFERENCES public.conversations(id)
  ON DELETE CASCADE;

-- 3.2 Registrations Foreign Key (CASCADE)
ALTER TABLE public.registrations 
  DROP CONSTRAINT IF EXISTS registrations_conversation_id_fkey;

ALTER TABLE public.registrations
  ADD CONSTRAINT registrations_conversation_id_fkey
  FOREIGN KEY (conversation_id)
  REFERENCES public.conversations(id)
  ON DELETE CASCADE;

-- Indexes
DROP INDEX IF EXISTS idx_profiles_org;
CREATE INDEX IF NOT EXISTS idx_profiles_org ON public.profiles(organization_id);

DROP INDEX IF EXISTS idx_vehicles_org;
CREATE INDEX IF NOT EXISTS idx_vehicles_org ON public.vehicles(organization_id);

DROP INDEX IF EXISTS idx_conversations_last_message_at;
CREATE INDEX IF NOT EXISTS idx_conversations_last_message_at ON public.conversations(last_message_at DESC);

DROP INDEX IF EXISTS idx_conversations_contact_phone;
CREATE INDEX IF NOT EXISTS idx_conversations_contact_phone ON public.conversations(contact_phone);

DROP INDEX IF EXISTS idx_messages_conversation_id;
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON public.messages(conversation_id);

-- =================================================================================================
-- 4. RLS POLICIES (Consolidated)
-- =================================================================================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boarding_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

-- Helper function for organization check
CREATE OR REPLACE FUNCTION public.get_auth_org_id()
RETURNS UUID AS $$
DECLARE
  org_id UUID;
BEGIN
  SELECT organization_id INTO org_id
  FROM public.profiles
  WHERE id = auth.uid();
  RETURN org_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Helper function for super admin check
CREATE OR REPLACE FUNCTION public.is_super_admin()
RETURNS BOOLEAN AS $$
DECLARE
  user_role TEXT;
BEGIN
  SELECT role INTO user_role
  FROM public.profiles
  WHERE id = auth.uid();
  -- Super admin logic: role is 'super_admin' OR (role is 'admin' AND organization_id IS NULL)
  RETURN user_role = 'super_admin' OR (user_role = 'admin' AND public.get_auth_org_id() IS NULL);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Profiles Policies
DROP POLICY IF EXISTS "Authenticated users can view all profiles" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Admins can update all profiles" ON public.profiles;
DROP POLICY IF EXISTS "Super Admins can do everything" ON public.profiles;

CREATE POLICY "Authenticated users can view all profiles" ON public.profiles FOR SELECT TO authenticated USING (true); -- Simplified visibility
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id);
CREATE POLICY "Super Admins can do everything" ON public.profiles FOR ALL TO authenticated USING (public.is_super_admin());

-- Vehicles Policies
DROP POLICY IF EXISTS "Authenticated users can view vehicles" ON public.vehicles;
DROP POLICY IF EXISTS "Authenticated users can insert vehicles" ON public.vehicles;
DROP POLICY IF EXISTS "Authenticated users can update vehicles" ON public.vehicles;
DROP POLICY IF EXISTS "Authenticated users can delete vehicles" ON public.vehicles;

CREATE POLICY "Authenticated users can view vehicles" ON public.vehicles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert vehicles" ON public.vehicles FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update vehicles" ON public.vehicles FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Authenticated users can delete vehicles" ON public.vehicles FOR DELETE TO authenticated USING (true);

-- Conversations Policies
DROP POLICY IF EXISTS "Authenticated users full access conversations" ON public.conversations;
CREATE POLICY "Authenticated users full access conversations" ON public.conversations FOR ALL TO authenticated USING (true);

-- Messages Policies
DROP POLICY IF EXISTS "Authenticated users full access messages" ON public.messages;
CREATE POLICY "Authenticated users full access messages" ON public.messages FOR ALL TO authenticated USING (true);

-- Registrations Policies
DROP POLICY IF EXISTS "Authenticated users full access registrations" ON public.registrations;
CREATE POLICY "Authenticated users full access registrations" ON public.registrations FOR ALL TO authenticated USING (true);

-- Boarding Locations Policies
DROP POLICY IF EXISTS "Authenticated users full access boarding_locations" ON public.boarding_locations;
CREATE POLICY "Authenticated users full access boarding_locations" ON public.boarding_locations FOR ALL TO authenticated USING (true);

-- Maintenance Policies
DROP POLICY IF EXISTS "Authenticated users full access maintenance" ON public.maintenance_records;
CREATE POLICY "Authenticated users full access maintenance" ON public.maintenance_records FOR ALL TO authenticated USING (true);

-- Audit Logs Policies
DROP POLICY IF EXISTS "Authenticated users full access audit_logs" ON public.audit_logs;
CREATE POLICY "Authenticated users full access audit_logs" ON public.audit_logs FOR ALL TO authenticated USING (true);

-- System Settings Policies
DROP POLICY IF EXISTS "Authenticated users full access system_settings" ON public.system_settings;
CREATE POLICY "Authenticated users full access system_settings" ON public.system_settings FOR ALL TO authenticated USING (true);

-- =================================================================================================
-- 5. DEFAULT DATA (Idempotent)
-- =================================================================================================

INSERT INTO public.system_settings (key, value, description)
VALUES 
  ('ai_persona', '"Assistente prestativo e profissional"', 'Personalidade do Agente de IA'),
  ('ai_creativity', '0.7', 'Nível de criatividade (Temperatura) de 0.0 a 1.0'),
  ('ai_supervision_level', '"medium"', 'Nível de intervenção no fluxo (low, medium, high)'),
  ('ai_instructions', '"Seja conciso e foque em agendar o transporte."', 'Instruções adicionais para o comportamento do Agente')
ON CONFLICT (key) DO NOTHING;

COMMIT;
